# -*- coding: utf-8 -*-
"""CIE3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sa7EEwLiQt1SS4FtzWkjRFnCGm5Ri4m7
"""

import pandas as pd
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import  train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,r2_score

data= fetch_california_housing()
data

df = pd.DataFrame(data.data, columns=data.feature_names)
print(df)

df.head()
df.describe()
df.shape
df.info()
df.isnull().sum()

df.describe()

X = df.drop('PRICE', axis=1)
y = df['PRICE']
X
y

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=4)
X_train
y_train

X_test
y_test

model=LinearRegression()
model.fit(X_train,y_train)

y_pred=model.predict(X_test)
y_pred

mse=mean_squared_error(y_test,y_pred)
mse

r2score=r2_score(y_test,y_pred)
r2score